---
output:
  html_document:
    bibliography: bibtex
    highlight: tango
    keep_md: yes
    theme: spacelab
---

### Last Update

```{r}
Sys.time()
```

***

### Data Set

The data sets have been directly retrived with an own Twitter application.

***

### Notices

This application is primarily a demo to show what is possible. 

In case of any questions related to this application, feel free to write [me a mail.][1]

***

### Used R Packages

```{r, eval=FALSE}
library(graph)
library(twitteR)
library(NLP)
library(tm)
library(shinyIncubator)
library(grid)
library(pvclust)
library(Rgraphviz)
library(qdapTools)
library(qdapRegex)
library(magrittr)
library(wordcloud)
library(RColorBrewer)
library(ggplot2)
library(RCurl)
library(bitops)
library(qdap)
library(devtools)
library(rjson)
library(bit64)
library(httr)
library(SnowballC)
library(slam)
library(RWeka)
library(rJava) 
library(RWekajars) 
```

***

### Last Session Info

```{r}
sessionInfo()
```



[1]: http://nierhoff.info/#contact "Contact"

***
